//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class User : IEntity
    {
    	private WebAppDatabase _db;
    
        [JsonIgnore]
    	public WebAppDatabase Database 
    	{ 
    		get
    		{
    			if (_db == null)
    				throw new NullReferenceException(string.Format("[Database] property null for User [ID:{0}]", ID));
    			return _db;
    		}
    		set
    		{
    			_db = value;
    		}
    	}
    
        public User(WebAppDatabase database) : this()
        {
            Database = database;
        }
    	partial void OnCreated();
    
        public User()
        {
            this.Orders = new HashSet<Order>();
    		OnCreated();
        }
    
        public int ID { get; set; }
        public int UserTypeID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
    
    
       [JsonIgnore] public virtual ICollection<Order> Orders { get; set; }
       [JsonIgnore] public virtual UserType UserType { get; set; }
    }
}
